### ISSUE TITLE
When given a block, the Trenni::Builder.fragment fails silently

### ISSUE THREAD

**Issue by isaacrowntree** [ioquatix/trenni#3]
```   
def row(options = {}, &block)
      options = @options.merge(options)

      Trenni::Builder.fragment do |builder|
        builder.inline(:dt) { builder.text title_for(options) }

        if block_given?
          builder.inline(:dd) { builder.capture(self, &block) }
        else
          builder.inline(:dd) { builder.text value_for(options) }
        end
      end
    end
```

Line 4 onwards never executes. Tested on 3.13.2.

**Comment by ioquatix** [comment]
Trenni uses a deferred approach to execution - the fragment only gets evaluated if it's actually used. Can you give me a bit more context as to what you are doing and how it's failing?

**Comment by isaacrowntree** [comment]
An example of usage is such: 

```
<?r f.row title: 'Title Test' do ?><a href="test-link">Test Link</a><?r end ?>
```

This line currently works: 

```
#{f.row :title => 'Test title', :value => "Test value"}
```

all I know is that up until recently the first line used to work but then we upgraded Trenni versions.

**Comment by ioquatix** [comment]
Can you tell me which version you were on and which version you are trying out/failing on? Assuming 3.13.2

**Comment by isaacrowntree** [comment]
OK after taking time to look back through our change history, it appears that this was the original code:

```
    def row(options = {}, &block)
      options = @options.merge(options)

      Trenni::Builder.fragment do |builder|
        builder.inline(:dt) { builder.text title_for(options) }

        if block_given?
          builder.inline(:dd) { builder.capture(self, &block) }
        else
          builder.inline(:dd) { builder.text value_for(options) }
        end
      end  >> block
    end
```
When upgrading from Trenni 3.9 to 3.13.2 with that code, the error is: ```undefined method `>>' for #<Trenni::Builder::Fragment:0x00007fdd8dbb61e8>```

I reproduced it and then downgraded Trenni back to 3.9 to resolve it. I will keep it at that until this issue is fixed.

**Comment by ioquatix** [comment]
Apologies, it has been a while.

I'm renaming the core parts of `Trenni` to `XRB`.

However, this looks like a legitimate bug. At the very least, I'll add a test case for it and see if we can reproduce.

**Comment by ioquatix** [comment]
I'm going to make a few notes on this issue.

Firstly, the last occurrence of `>>` is here:

https://github.com/socketry/xrb/blob/9e6f2fbfb403a03c1bd6f1fa99d718c5a35647ce/lib/trenni/template.rb#L31-L44

I regret that I may have removed something that caused incompatibility. Perhaps I'll restore this code path.

**Comment by ioquatix** [comment]
It was changed in https://github.com/socketry/xrb/commit/d799fd27938dd59cc8b31438982507736ce86496

**Comment by ioquatix** [comment]
Okay, I've fixed support for this in `xrb`. The utopia framework will be updated to use xrb, and this project should be considered unmaintained from now on, replaced by `xrb` which is just a fork of this work with a different name.
